// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfYdME0vDoHEyN7VlGAJvKRjM0Tr-YpE',
    appId: '1:562734395057:web:aa21942ce0fd2dafb77c90',
    messagingSenderId: '562734395057',
    projectId: 'mixin-c9ebd',
    authDomain: 'mixin-c9ebd.firebaseapp.com',
    storageBucket: 'mixin-c9ebd.appspot.com',
    measurementId: 'G-05ZMYLQNQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdACtLwRLiGlNjPIhxmvxpwG_LQ2SrLk',
    appId: '1:562734395057:android:f149039bbbae8bffb77c90',
    messagingSenderId: '562734395057',
    projectId: 'mixin-c9ebd',
    storageBucket: 'mixin-c9ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaOxhfU4T718b5IKC8AjbvJvP0B3Xmts',
    appId: '1:562734395057:ios:b8953d470969f0b8b77c90',
    messagingSenderId: '562734395057',
    projectId: 'mixin-c9ebd',
    storageBucket: 'mixin-c9ebd.appspot.com',
    iosBundleId: 'com.teamMixin.mixinMac2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaOxhfU4T718b5IKC8AjbvJvP0B3Xmts',
    appId: '1:562734395057:ios:579fc8a794f7ee02b77c90',
    messagingSenderId: '562734395057',
    projectId: 'mixin-c9ebd',
    storageBucket: 'mixin-c9ebd.appspot.com',
    iosBundleId: 'com.example.mixinMac2.RunnerTests',
  );
}
